// Autogenerated by Thrift Compiler (0.10.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package userservice

import (
	"bytes"
	"fmt"
	"thrift/proto/req"
	"thrift/proto/resp"

	"git.apache.org/thrift.git/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var _ = req.GoUnusedProtection__
var _ = resp.GoUnusedProtection__

func init() {
}
